version: "3.8"

services:
  postgres:
    image: 'postgres:15.2'
    container_name: 'postgres'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    expose:
      - '5432'